CREATE TABLE `assignment_templates` (
  `id` text PRIMARY KEY NOT NULL,
  `organization_id` text,
  `title` text NOT NULL,
  `description` text,
  `content_type` text NOT NULL,
  `content_ref` text,
  `tags` text DEFAULT '[]' NOT NULL,
  `is_public` integer DEFAULT 0 NOT NULL,
  `created_by_user_id` text,
  FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
  FOREIGN KEY (`created_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX `assignment_templates_org_idx` ON `assignment_templates` (`organization_id`);
--> statement-breakpoint
CREATE INDEX `assignment_templates_user_idx` ON `assignment_templates` (`created_by_user_id`);
--> statement-breakpoint
CREATE INDEX `assignment_templates_public_idx` ON `assignment_templates` (`is_public`);
--> statement-breakpoint
CREATE INDEX `assignment_templates_content_type_idx` ON `assignment_templates` (`content_type`);
--> statement-breakpoint
INSERT INTO `assignment_templates` (`id`, `organization_id`, `title`, `description`, `content_type`, `content_ref`, `tags`, `is_public`, `created_by_user_id`) VALUES
  ('tpl_public_us_history_revolution_essay', NULL, 'US History Essay: Causes of the American Revolution', 'Three short essay prompts on major causes, resistance, and outcomes of the Revolution.', 'essay_questions', '{"questions":["Explain two major causes of the American Revolution.","How did pamphlets, protests, and boycotts influence colonial resistance?","What changed in government after independence?"]}', '["subject:history","topic:us-history","grade:6","grade:7","grade:8","skill:writing"]', 1, NULL),
  ('tpl_public_us_history_constitution_essay', NULL, 'US History Essay: The Constitution in Practice', 'Structured writing prompts about the Constitution, federalism, and rights.', 'essay_questions', '{"questions":["Why did the framers want a stronger national government?","How does the Constitution divide power between state and federal governments?","Why are the Bill of Rights still important today?"]}', '["subject:history","topic:us-history","grade:7","grade:8","grade:9","skill:writing"]', 1, NULL),
  ('tpl_public_us_history_civil_war_essay', NULL, 'US History Essay: Civil War and Reconstruction', 'Essay questions covering causes of the war and the challenges of Reconstruction.', 'essay_questions', '{"questions":["What were the main political and economic causes of the Civil War?","How did the Civil War change the nation?","What problems did Reconstruction try to solve, and why was it difficult?"]}', '["subject:history","topic:us-history","grade:7","grade:8","grade:9","skill:writing"]', 1, NULL),
  ('tpl_public_world_history_egypt_essay', NULL, 'World History Essay: Ancient Egypt', 'Reading response style questions about geography, leadership, and culture in Ancient Egypt.', 'essay_questions', '{"questions":["How did the Nile River shape life in Ancient Egypt?","What roles did pharaohs and priests play in Egyptian society?","What can monuments and tombs teach us about Egyptian beliefs?"]}', '["subject:history","topic:world-history","grade:5","grade:6","grade:7","skill:writing"]', 1, NULL),
  ('tpl_public_math_algebra_basics_quiz', NULL, 'Math Quiz: Basic Algebra Skills Check', 'A five-question quiz on evaluating expressions and solving simple equations.', 'quiz', '{"title":"Basic Algebra Skills Check","questions":[{"question":"What is 3x + 2 when x = 4?","options":["10","12","14","16"],"answerIndex":2,"explanation":"Substitute 4 for x to get 3(4) + 2 = 14."},{"question":"Solve: x + 7 = 12","options":["3","4","5","6"],"answerIndex":2,"explanation":"Subtract 7 from both sides."},{"question":"Which expression is equivalent to 5a + 5b?","options":["5(a + b)","10ab","a + b + 5","5ab"],"answerIndex":0,"explanation":"Factor out the common factor 5."},{"question":"Solve: 2y = 18","options":["7","8","9","10"],"answerIndex":2,"explanation":"Divide both sides by 2."},{"question":"What is the coefficient of n in 9n - 4?","options":["-4","4","9","n"],"answerIndex":2,"explanation":"The coefficient is the number multiplying the variable."}]}', '["subject:math","topic:algebra","grade:6","grade:7","grade:8","skill:practice"]', 1, NULL),
  ('tpl_public_math_one_step_quiz', NULL, 'Math Quiz: Solving One-Step Equations', 'Quick practice with addition, subtraction, multiplication, and division equations.', 'quiz', '{"title":"Solving One-Step Equations","questions":[{"question":"Solve: x - 4 = 9","options":["5","11","13","36"],"answerIndex":2,"explanation":"Add 4 to both sides."},{"question":"Solve: n + 15 = 23","options":["6","7","8","9"],"answerIndex":2,"explanation":"Subtract 15 from 23."},{"question":"Solve: 6m = 42","options":["6","7","8","9"],"answerIndex":1,"explanation":"Divide 42 by 6."},{"question":"Solve: p / 5 = 3","options":["8","10","15","20"],"answerIndex":2,"explanation":"Multiply both sides by 5."},{"question":"Which inverse operation solves x + 12 = 20?","options":["Add 12","Subtract 12","Multiply by 12","Divide by 12"],"answerIndex":1,"explanation":"Subtraction undoes addition."}]}', '["subject:math","topic:algebra","grade:5","grade:6","grade:7","skill:practice"]', 1, NULL),
  ('tpl_public_math_fractions_quiz', NULL, 'Math Quiz: Fractions and Mixed Numbers', 'A general review of adding, comparing, and simplifying fractions.', 'quiz', '{"title":"Fractions and Mixed Numbers Review","questions":[{"question":"Which fraction is equal to 1/2?","options":["2/3","3/6","4/5","5/8"],"answerIndex":1,"explanation":"Three sixths simplifies to one half."},{"question":"What is 1/4 + 2/4?","options":["2/8","3/4","3/8","1/2"],"answerIndex":1,"explanation":"Add the numerators when the denominators are the same."},{"question":"Which is greater?","options":["1/3","1/5","They are equal","Not enough information"],"answerIndex":0,"explanation":"With the same numerator, the smaller denominator makes the larger fraction."},{"question":"Simplify 6/8.","options":["1/2","2/3","3/4","4/5"],"answerIndex":2,"explanation":"Divide numerator and denominator by 2."},{"question":"Convert 7/3 to a mixed number.","options":["1 1/3","2 1/3","2 2/3","3 1/3"],"answerIndex":1,"explanation":"Three goes into seven two times with one left over."}]}', '["subject:math","topic:fractions","grade:4","grade:5","grade:6","skill:practice"]', 1, NULL),
  ('tpl_public_math_geometry_quiz', NULL, 'Math Quiz: Geometry Vocabulary Warm-Up', 'Multiple-choice geometry review for angles, polygons, and perimeter.', 'quiz', '{"title":"Geometry Vocabulary Warm-Up","questions":[{"question":"How many sides does a hexagon have?","options":["5","6","7","8"],"answerIndex":1,"explanation":"Hexagons have six sides."},{"question":"A right angle measures","options":["45 degrees","60 degrees","90 degrees","180 degrees"],"answerIndex":2,"explanation":"A right angle is 90 degrees."},{"question":"Perimeter means","options":["space inside a shape","distance around a shape","number of angles","length times width"],"answerIndex":1,"explanation":"Perimeter is the total distance around the outside."},{"question":"A triangle with all equal sides is","options":["scalene","right","equilateral","isosceles"],"answerIndex":2,"explanation":"Equilateral triangles have three equal sides."},{"question":"Parallel lines","options":["cross at one point","never meet","form a right angle","are always vertical"],"answerIndex":1,"explanation":"Parallel lines stay the same distance apart and do not intersect."}]}', '["subject:math","topic:geometry","grade:4","grade:5","grade:6","skill:practice"]', 1, NULL),
  ('tpl_public_science_cell_reading', NULL, 'Biology Reading: Cells (Wikipedia)', 'Assign a reference reading about cell structure and function.', 'url', 'https://en.wikipedia.org/wiki/Cell_(biology)', '["subject:science","topic:biology","grade:7","grade:8","grade:9","skill:reading"]', 1, NULL),
  ('tpl_public_science_photosynthesis_reading', NULL, 'Biology Reading: Photosynthesis (Wikipedia)', 'Direct students to a background reading on photosynthesis and energy transfer.', 'url', 'https://en.wikipedia.org/wiki/Photosynthesis', '["subject:science","topic:biology","grade:6","grade:7","grade:8","skill:reading"]', 1, NULL),
  ('tpl_public_science_water_cycle_reading', NULL, 'Earth Science Reading: Water Cycle (Wikipedia)', 'A general reading assignment on evaporation, condensation, and precipitation.', 'url', 'https://en.wikipedia.org/wiki/Water_cycle', '["subject:science","topic:earth-science","grade:4","grade:5","grade:6","skill:reading"]', 1, NULL),
  ('tpl_public_science_solar_system_reading', NULL, 'Astronomy Reading: Solar System (Wikipedia)', 'Assign a broad reading on planets, orbits, and the structure of the solar system.', 'url', 'https://en.wikipedia.org/wiki/Solar_System', '["subject:science","topic:astronomy","grade:4","grade:5","grade:6","skill:reading"]', 1, NULL),
  ('tpl_public_language_arts_parts_of_speech', NULL, 'Grammar Worksheet: Parts of Speech Practice', 'A ready-to-edit grammar practice page covering nouns, verbs, adjectives, and adverbs.', 'report', '<h2>Parts of Speech Practice</h2><p>Directions: Read each sentence and identify the requested part of speech.</p><ol><li>Circle the noun in each sentence.</li><li>Underline the verb in each sentence.</li><li>Write one adjective and one adverb to improve each sentence.</li></ol><h3>Extension</h3><p>Write three original sentences that include a noun, verb, adjective, and adverb.</p>', '["subject:language-arts","topic:grammar","grade:3","grade:4","grade:5","skill:practice"]', 1, NULL),
  ('tpl_public_language_arts_sentence_types', NULL, 'Grammar Worksheet: Sentence Types and Punctuation', 'Sentence sorting and punctuation practice for statements, questions, commands, and exclamations.', 'report', '<h2>Sentence Types and Punctuation</h2><p>Directions: Label each sentence as a statement, question, command, or exclamation.</p><ol><li>Add the correct end punctuation.</li><li>Rewrite two sentences to change the sentence type.</li><li>Explain how punctuation helps the reader understand tone.</li></ol>', '["subject:language-arts","topic:grammar","grade:3","grade:4","grade:5","skill:practice"]', 1, NULL),
  ('tpl_public_science_experiment_rubric', NULL, 'Science Experiment Report Rubric', 'A simple lab report structure with grading criteria for question, method, data, and conclusion.', 'report', '<h2>Science Experiment Report</h2><p>Complete each section clearly and neatly.</p><h3>Required Sections</h3><ol><li>Question or hypothesis</li><li>Materials</li><li>Procedure</li><li>Observations and data</li><li>Conclusion</li></ol><h3>Rubric</h3><ul><li>4 points: Clear question and logical prediction</li><li>4 points: Complete procedure with sequence words</li><li>4 points: Accurate data table or notes</li><li>4 points: Conclusion explains results using evidence</li><li>4 points: Clean presentation and correct spelling</li></ul>', '["subject:science","topic:scientific-method","grade:4","grade:5","grade:6","grade:7","skill:writing"]', 1, NULL),
  ('tpl_public_language_arts_book_report', NULL, 'Book Report Template', 'A general book report scaffold with summary and analysis prompts.', 'report', '<h2>Book Report</h2><p>Use complete sentences and support your ideas with details from the book.</p><ol><li>Title, author, and genre</li><li>Setting and main characters</li><li>Summary of the main conflict</li><li>Favorite scene and why it matters</li><li>Theme or lesson</li><li>Your rating and recommendation</li></ol>', '["subject:language-arts","topic:literature","grade:4","grade:5","grade:6","skill:writing"]', 1, NULL),
  ('tpl_public_literature_response_essay', NULL, 'Literature Response: Novel Reflection Questions', 'Essay prompts for chapter books, novels, or read-aloud discussions.', 'essay_questions', '{"questions":["How does the main character change from the beginning to the end of the story?","What conflict drives the story forward, and how is it resolved?","What theme or lesson does the author want the reader to understand?"]}', '["subject:language-arts","topic:literature","grade:5","grade:6","grade:7","grade:8","skill:writing"]', 1, NULL),
  ('tpl_public_civics_branches_essay', NULL, 'Civics Writing: Three Branches of Government', 'Writing prompts on checks and balances and the role of each branch.', 'essay_questions', '{"questions":["What is the main job of the legislative branch?","How do the executive and judicial branches limit the power of the legislative branch?","Why are checks and balances important in a constitutional government?"]}', '["subject:social-studies","topic:civics","grade:5","grade:6","grade:7","skill:writing"]', 1, NULL),
  ('tpl_public_world_languages_spanish_quiz', NULL, 'Spanish Quiz: Intro Vocabulary Check', 'Basic vocabulary practice for greetings, colors, and classroom words.', 'quiz', '{"title":"Intro Spanish Vocabulary Check","questions":[{"question":"What does hola mean?","options":["Goodbye","Hello","Please","Thank you"],"answerIndex":1,"explanation":"Hola is the common greeting for hello."},{"question":"Which word means red?","options":["azul","verde","rojo","negro"],"answerIndex":2,"explanation":"Rojo means red."},{"question":"What does libro mean?","options":["book","pencil","desk","window"],"answerIndex":0,"explanation":"Libro means book."},{"question":"Which phrase means thank you?","options":["por favor","de nada","gracias","buenos dias"],"answerIndex":2,"explanation":"Gracias means thank you."},{"question":"What does escuela mean?","options":["teacher","school","friend","music"],"answerIndex":1,"explanation":"Escuela means school."}]}', '["subject:world-languages","topic:spanish","grade:4","grade:5","grade:6","grade:7","skill:practice"]', 1, NULL),
  ('tpl_public_health_nutrition_report', NULL, 'Health Assignment: Nutrition Label Analysis', 'A short written analysis of serving size, sugar, protein, and marketing claims.', 'report', '<h2>Nutrition Label Analysis</h2><p>Choose one packaged food item and study the nutrition label.</p><ol><li>Record the serving size and servings per container.</li><li>List calories, sugar, protein, and sodium.</li><li>Explain whether the label presents the food as healthy and why.</li><li>Write one change you would make to improve the product.</li></ol>', '["subject:health","topic:nutrition","grade:5","grade:6","grade:7","skill:analysis"]', 1, NULL);
