/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SkillTreesRouteImport } from './routes/skill-trees'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectStudentRouteImport } from './routes/select-student'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as GradebookRouteImport } from './routes/gradebook'
import { Route as CurriculumBuilderRouteImport } from './routes/curriculum-builder'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillTreeTreeIdRouteImport } from './routes/skill-tree.$treeId'
import { Route as RewardsTrackIdRouteImport } from './routes/rewards.$trackId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillTreesRoute = SkillTreesRouteImport.update({
  id: '/skill-trees',
  path: '/skill-trees',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectStudentRoute = SelectStudentRouteImport.update({
  id: '/select-student',
  path: '/select-student',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const GradebookRoute = GradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumBuilderRoute = CurriculumBuilderRouteImport.update({
  id: '/curriculum-builder',
  path: '/curriculum-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillTreeTreeIdRoute = SkillTreeTreeIdRouteImport.update({
  id: '/skill-tree/$treeId',
  path: '/skill-tree/$treeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsTrackIdRoute = RewardsTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => RewardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/curriculum-builder': typeof CurriculumBuilderRoute
  '/gradebook': typeof GradebookRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRouteWithChildren
  '/select-student': typeof SelectStudentRoute
  '/settings': typeof SettingsRoute
  '/skill-trees': typeof SkillTreesRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/templates': typeof TemplatesRoute
  '/rewards/$trackId': typeof RewardsTrackIdRoute
  '/skill-tree/$treeId': typeof SkillTreeTreeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/curriculum-builder': typeof CurriculumBuilderRoute
  '/gradebook': typeof GradebookRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRouteWithChildren
  '/select-student': typeof SelectStudentRoute
  '/settings': typeof SettingsRoute
  '/skill-trees': typeof SkillTreesRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/templates': typeof TemplatesRoute
  '/rewards/$trackId': typeof RewardsTrackIdRoute
  '/skill-tree/$treeId': typeof SkillTreeTreeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/curriculum-builder': typeof CurriculumBuilderRoute
  '/gradebook': typeof GradebookRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRouteWithChildren
  '/select-student': typeof SelectStudentRoute
  '/settings': typeof SettingsRoute
  '/skill-trees': typeof SkillTreesRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
  '/templates': typeof TemplatesRoute
  '/rewards/$trackId': typeof RewardsTrackIdRoute
  '/skill-tree/$treeId': typeof SkillTreeTreeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assignments'
    | '/classes'
    | '/curriculum-builder'
    | '/gradebook'
    | '/lessons'
    | '/login'
    | '/planner'
    | '/register'
    | '/rewards'
    | '/select-student'
    | '/settings'
    | '/skill-trees'
    | '/student'
    | '/students'
    | '/templates'
    | '/rewards/$trackId'
    | '/skill-tree/$treeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assignments'
    | '/classes'
    | '/curriculum-builder'
    | '/gradebook'
    | '/lessons'
    | '/login'
    | '/planner'
    | '/register'
    | '/rewards'
    | '/select-student'
    | '/settings'
    | '/skill-trees'
    | '/student'
    | '/students'
    | '/templates'
    | '/rewards/$trackId'
    | '/skill-tree/$treeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assignments'
    | '/classes'
    | '/curriculum-builder'
    | '/gradebook'
    | '/lessons'
    | '/login'
    | '/planner'
    | '/register'
    | '/rewards'
    | '/select-student'
    | '/settings'
    | '/skill-trees'
    | '/student'
    | '/students'
    | '/templates'
    | '/rewards/$trackId'
    | '/skill-tree/$treeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ClassesRoute: typeof ClassesRoute
  CurriculumBuilderRoute: typeof CurriculumBuilderRoute
  GradebookRoute: typeof GradebookRoute
  LessonsRoute: typeof LessonsRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  RegisterRoute: typeof RegisterRoute
  RewardsRoute: typeof RewardsRouteWithChildren
  SelectStudentRoute: typeof SelectStudentRoute
  SettingsRoute: typeof SettingsRoute
  SkillTreesRoute: typeof SkillTreesRoute
  StudentRoute: typeof StudentRoute
  StudentsRoute: typeof StudentsRoute
  TemplatesRoute: typeof TemplatesRoute
  SkillTreeTreeIdRoute: typeof SkillTreeTreeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-trees': {
      id: '/skill-trees'
      path: '/skill-trees'
      fullPath: '/skill-trees'
      preLoaderRoute: typeof SkillTreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-student': {
      id: '/select-student'
      path: '/select-student'
      fullPath: '/select-student'
      preLoaderRoute: typeof SelectStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradebook': {
      id: '/gradebook'
      path: '/gradebook'
      fullPath: '/gradebook'
      preLoaderRoute: typeof GradebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum-builder': {
      id: '/curriculum-builder'
      path: '/curriculum-builder'
      fullPath: '/curriculum-builder'
      preLoaderRoute: typeof CurriculumBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-tree/$treeId': {
      id: '/skill-tree/$treeId'
      path: '/skill-tree/$treeId'
      fullPath: '/skill-tree/$treeId'
      preLoaderRoute: typeof SkillTreeTreeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/$trackId': {
      id: '/rewards/$trackId'
      path: '/$trackId'
      fullPath: '/rewards/$trackId'
      preLoaderRoute: typeof RewardsTrackIdRouteImport
      parentRoute: typeof RewardsRoute
    }
  }
}

interface RewardsRouteChildren {
  RewardsTrackIdRoute: typeof RewardsTrackIdRoute
}

const RewardsRouteChildren: RewardsRouteChildren = {
  RewardsTrackIdRoute: RewardsTrackIdRoute,
}

const RewardsRouteWithChildren =
  RewardsRoute._addFileChildren(RewardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssignmentsRoute: AssignmentsRoute,
  ClassesRoute: ClassesRoute,
  CurriculumBuilderRoute: CurriculumBuilderRoute,
  GradebookRoute: GradebookRoute,
  LessonsRoute: LessonsRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  RegisterRoute: RegisterRoute,
  RewardsRoute: RewardsRouteWithChildren,
  SelectStudentRoute: SelectStudentRoute,
  SettingsRoute: SettingsRoute,
  SkillTreesRoute: SkillTreesRoute,
  StudentRoute: StudentRoute,
  StudentsRoute: StudentsRoute,
  TemplatesRoute: TemplatesRoute,
  SkillTreeTreeIdRoute: SkillTreeTreeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
