/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectStudentRouteImport } from './routes/select-student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GradebookRouteImport } from './routes/gradebook'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectStudentRoute = SelectStudentRouteImport.update({
  id: '/select-student',
  path: '/select-student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GradebookRoute = GradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/gradebook': typeof GradebookRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/select-student': typeof SelectStudentRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/gradebook': typeof GradebookRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/select-student': typeof SelectStudentRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/gradebook': typeof GradebookRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/select-student': typeof SelectStudentRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/students': typeof StudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assignments'
    | '/classes'
    | '/gradebook'
    | '/login'
    | '/planner'
    | '/register'
    | '/select-student'
    | '/settings'
    | '/student'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assignments'
    | '/classes'
    | '/gradebook'
    | '/login'
    | '/planner'
    | '/register'
    | '/select-student'
    | '/settings'
    | '/student'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assignments'
    | '/classes'
    | '/gradebook'
    | '/login'
    | '/planner'
    | '/register'
    | '/select-student'
    | '/settings'
    | '/student'
    | '/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ClassesRoute: typeof ClassesRoute
  GradebookRoute: typeof GradebookRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  RegisterRoute: typeof RegisterRoute
  SelectStudentRoute: typeof SelectStudentRoute
  SettingsRoute: typeof SettingsRoute
  StudentRoute: typeof StudentRoute
  StudentsRoute: typeof StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-student': {
      id: '/select-student'
      path: '/select-student'
      fullPath: '/select-student'
      preLoaderRoute: typeof SelectStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradebook': {
      id: '/gradebook'
      path: '/gradebook'
      fullPath: '/gradebook'
      preLoaderRoute: typeof GradebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssignmentsRoute: AssignmentsRoute,
  ClassesRoute: ClassesRoute,
  GradebookRoute: GradebookRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  RegisterRoute: RegisterRoute,
  SelectStudentRoute: SelectStudentRoute,
  SettingsRoute: SettingsRoute,
  StudentRoute: StudentRoute,
  StudentsRoute: StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
